export { getAssignments } from "@/lib/supabase/crud/assignments";
export { getCurrentUser } from "@/lib/supabase/crud/auth";
export { getDeadlines } from "@/lib/supabase/crud/deadline";
export { getExams } from "@/lib/supabase/crud/exam";
export { getLectures } from "@/lib/supabase/crud/lecture";
export { getNotes, getNotesByUserId } from "@/lib/supabase/crud/note";
export { getNotifications } from "@/lib/supabase/crud/notification";
export { getPlans } from "@/lib/supabase/crud/plan";
export { getProgress } from "@/lib/supabase/crud/progress";
export { getTasks } from "@/lib/supabase/crud/task";
